language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    # Release steps
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
