# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Run tests and publish

on:
  push:
    branches:
      - master
      - development
      - beta
  pull_request:

jobs:
  run-tests-node-12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install depencencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Send data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Enable docker buildx
        id: buildx
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: crazy-max/ghaction-docker-buildx@v2
        with:
          version: latest
      - name: Login to docker
        if: steps.semantic.outputs.new_release_published == 'true'
        run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to docker with buildx as latest
        if: steps.semantic.outputs.new_release_published == 'true' && github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --push \
            -t svrooij/smartmeter:latest \
            -t svrooij/smartmeter:${{ steps.semantic.outputs.new_release_version }} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=${{ steps.semantic.outputs.new_release_version }} \
            --build-arg VSC_REF=$(echo ${GITHUB_SHA} | cut -c1-8) \
            .
      - name: Publish to docker with buildx as latest
        if: steps.semantic.outputs.new_release_published == 'true' && github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --push \
            -t svrooij/smartmeter:beta \
            -t svrooij/smartmeter:${{ steps.semantic.outputs.new_release_version }} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=${{ steps.semantic.outputs.new_release_version }} \
            --build-arg VSC_REF=$(echo ${GITHUB_SHA} | cut -c1-8) \
            .
